/* 학회 데이터 — 2026-09-06 기준 각 학회 공식 홈페이지 확인분.
   갱신 시 이 파일만 교체하면 됨 (아티팩트 판 CONFS/TBA와 동일 구조). */

const CATS = {dem:{label:"치매·신경퇴행", varName:"--dem"}, neuro:{label:"신경과학·신경과", varName:"--neuro"}, psych:{label:"정신과학", varName:"--psych"}, ai:{label:"의료 AI", varName:"--ai"}};

/* status: ok=확정, part=일부 미정 */
const CONFS = [
 {id:"acnp", cat:"psych", acro:"ACNP 2027", full:"American College of Neuropsychopharmacology · 65th Annual Meeting",
  start:"2027-01-10", end:"2027-01-13", dateKo:"1월 10–13일", city:"샌디에이고", country:"미국", flag:"🇺🇸",
  venue:"Manchester Grand Hyatt", hybrid:false, status:"ok",
  scale:"신경정신약리학 최상위 학회. 회원·초청 중심 참석(비회원은 회원 스폰서 필요). 12월→1월 개최로 이동됨.",
  url:"https://acnp.org/annual-meeting/dates-locations/", dl:[{l:"초록 마감", d:null, note:"미공지"}]},
 {id:"hai", cat:"dem", acro:"HAI 2027", full:"Human Amyloid Imaging",
  start:"2027-01-13", end:"2027-01-15", dateKo:"1월 13–15일", city:"산후안", country:"푸에르토리코", flag:"🇵🇷",
  venue:"Puerto Rico Convention Center", hybrid:false, status:"ok",
  scale:"아밀로이드·타우 PET와 이미징 바이오마커 특화, 약 500명 규모의 밀도 높은 학회.",
  url:"https://hai.worldeventsforum.com/",
  dl:[{l:"초록 접수 시작", d:"2026-10-02"},{l:"초록 마감", d:"2026-10-23"},{l:"채택 통보", d:"2026-11-25", note:"경"}]},
 {id:"adpd", cat:"dem", acro:"AD/PD 2027", full:"Intl. Conference on Alzheimer's and Parkinson's Diseases",
  start:"2027-03-16", end:"2027-03-20", dateKo:"3월 16–20일", city:"바르셀로나", country:"스페인", flag:"🇪🇸",
  venue:"CCIB · 준확인(공식 사이트 미표기)", hybrid:true, status:"ok",
  scale:"AD·PD 통합 학회(Kenes 주관), 수천 명 규모. 병태기전·중개연구·신약개발 강세.",
  url:"https://adpd.kenes.com/", dl:[{l:"초록 마감(연장)", d:"2026-09-08"}]},
 {id:"cns", cat:"neuro", acro:"CNS 2027", full:"Cognitive Neuroscience Society Annual Meeting",
  start:"2027-03-20", end:"2027-03-23", dateKo:"3월 20–23일", city:"보스턴", country:"미국", flag:"🇺🇸",
  venue:null, hybrid:false, status:"ok",
  scale:"인간 인지신경과학 전문, 약 1,500–2,000명. 기억·인지노화 연구와 접점이 큼.",
  url:"https://www.cogneurosociety.org/annual-meeting/",
  dl:[{l:"심포지엄 마감", d:"2026-09-14"},{l:"포스터 초록 마감", d:"2026-11-03"},{l:"등록 오픈", d:"2026-10-23"},{l:"조기등록 마감", d:"2027-01-05"},{l:"정규등록 마감", d:"2027-02-12"}]},
 {id:"epa", cat:"psych", acro:"EPA 2027", full:"35th European Congress of Psychiatry",
  start:"2027-04-03", end:"2027-04-06", dateKo:"4월 3–6일", city:"피렌체", country:"이탈리아", flag:"🇮🇹",
  venue:"Fortezza da Basso", hybrid:false, status:"ok",
  scale:"유럽정신의학회. 2027 주제 \"Innovating Mental Health: Towards Personalised and Integrated Care\".",
  url:"https://www.europsy.net/epa-2027/", dl:[{l:"초록 마감", d:"2026-09-21"}]},
 {id:"ickda", cat:"dem", acro:"IC-KDA 2027", full:"AAIC Advancements: IC-KDA (Alzheimer's Association 위성학회)",
  start:"2027-04-16", end:"2027-04-17", dateKo:"4월 16–17일", city:"서울", country:"대한민국", flag:"🇰🇷",
  venue:null, hybrid:true, status:"ok",
  scale:"국내 개최 — 참석 부담이 가장 적음. 대한치매학회·Alzheimer's Association 연계 국제학회.",
  url:"https://www.alz.org/research/for_researchers/scientific-conferences", dl:[{l:"초록 마감", d:null, note:"미공지"}]},
 {id:"aagp", cat:"psych", acro:"AAGP 2027", full:"American Association for Geriatric Psychiatry Annual Meeting",
  start:"2027-04-16", end:"2027-04-19", dateKo:"4월 16–19일", city:"샌디에이고", country:"미국", flag:"🇺🇸",
  venue:"Sheraton San Diego Resort", hybrid:false, status:"ok",
  scale:"미국 노인정신의학회, 수백–천 명 규모. 2027 주제 \"Connecting and Collaborating to Advance Geriatric Mental Health\".",
  url:"https://aagponline.org/event/2027-annual-meeting/", dl:[{l:"초록 마감", d:null, note:"미공지"}]},
 {id:"aan", cat:"neuro", acro:"AAN 2027", full:"American Academy of Neurology Annual Meeting",
  start:"2027-05-01", end:"2027-05-05", dateKo:"5월 1–5일", city:"워싱턴 DC", country:"미국", flag:"🇺🇸",
  venue:null, hybrid:true, status:"ok",
  scale:"세계 최대 임상신경과 학회(1만+ 명). 치매·AD 치료제 임상 최신 데이터의 주요 발표 무대. ※ APA와 일정 완전 중복.",
  url:"https://www.aan.com/events/annual-meeting",
  dl:[{l:"초록 마감", d:"2026-10-13"},{l:"레이트브레이킹 마감", d:"2027-02-10"},{l:"등록 오픈", d:null, note:"2026년 11월 초"}]},
 {id:"apa", cat:"psych", acro:"APA 2027", full:"American Psychiatric Association · 180th Annual Meeting",
  start:"2027-05-01", end:"2027-05-05", dateKo:"5월 1–5일", city:"뉴욕", country:"미국", flag:"🇺🇸",
  venue:"Javits Center", hybrid:false, status:"ok",
  scale:"세계 최대 정신의학 학회(1만+ 명). ※ AAN과 일정 완전 중복, SOBP(시카고)와 연속 주간.",
  url:"https://www.psychiatry.org/psychiatrists/meetings/annual-meeting", dl:[{l:"초록 마감", d:null, note:"미공지 · 통상 전년 가을 접수"}]},
 {id:"sobp", cat:"psych", acro:"SOBP 2027", full:"Society of Biological Psychiatry Annual Meeting",
  start:"2027-05-06", end:"2027-05-08", dateKo:"5월 6–8일", city:"시카고", country:"미국", flag:"🇺🇸",
  venue:"Sheraton Grand Chicago Riverwalk", hybrid:false, status:"ok",
  scale:"생물정신의학 중심(Biological Psychiatry 저널 학회). 2027 주제 \"The Metabolic Brain\".",
  url:"https://sobp.org/", dl:[{l:"초록 마감", d:null, note:"미공지"}]},
 {id:"fens", cat:"neuro", acro:"FENS Regional 2027", full:"FENS Regional Meeting (FRM2027) — Forum은 짝수 해 개최",
  start:"2027-05-26", end:"2027-05-29", dateKo:"5월 26–29일", city:"이스탄불", country:"튀르키예", flag:"🇹🇷",
  venue:"Lütfi Kırdar ICEC", hybrid:false, status:"ok",
  scale:"유럽 신경과학 지역대회(1–2천 명). FENS Forum은 격년(차기 2028)이라 2027년엔 Regional만 개최.",
  url:"https://frm2027.org/", dl:[{l:"초록 마감", d:null, note:"미공지 · 심포지엄 공모 진행 중"}]},
 {id:"tau", cat:"dem", acro:"Tau Global 2027", full:"Tau Global Conference (Alzheimer's Association · CurePSP · Rainwater)",
  start:"2027-06-03", end:"2027-06-04", dateKo:"6월 3–4일", city:"도쿄", country:"일본", flag:"🇯🇵",
  venue:null, hybrid:true, status:"ok",
  scale:"타우 생물학·치료 특화 소규모 학회. 아시아 개최라 한국에서 접근성 좋음.",
  url:"https://www.alz.org/tau", dl:[{l:"초록 마감", d:null, note:"미공지"}]},
 {id:"ean", cat:"neuro", acro:"EAN 2027", full:"European Academy of Neurology · 13th Congress",
  start:"2027-06-12", end:"2027-06-15", dateKo:"6월 12–15일", city:"예테보리", country:"스웨덴", flag:"🇸🇪",
  venue:"Gothia Towers", hybrid:false, status:"ok",
  scale:"유럽 임상신경과 대표 학회(7–9천 명). 2027 주제 \"Transforming Neurology: Embracing Every Brain\". ILBDC(스톡홀름)와 연계 가능.",
  url:"https://www.ean.org/congress2027",
  dl:[{l:"초록 마감", d:"2027-01-14"},{l:"조기등록 마감", d:"2027-04-14"}]},
 {id:"ilbdc", cat:"dem", acro:"ILBDC 2027", full:"International Lewy Body Dementia Conference",
  start:"2027-06-16", end:"2027-06-18", dateKo:"6월 16–18일", city:"스톡홀름", country:"스웨덴", flag:"🇸🇪",
  venue:null, hybrid:false, status:"ok",
  scale:"DLB·PDD 특화 국제학회. EAN 예테보리(6/12–15) 직후라 한 번의 출장으로 연계 가능.",
  url:"https://ic-dlb.com/", dl:[{l:"초록 마감", d:null, note:"미공지"}]},
 {id:"ohbm", cat:"neuro", acro:"OHBM 2027", full:"Organization for Human Brain Mapping Annual Meeting",
  start:"2027-06-26", end:"2027-06-30", dateKo:"6월 26–30일", city:"토론토", country:"캐나다", flag:"🇨🇦",
  venue:"Metro Toronto Convention Centre", hybrid:false, status:"ok",
  scale:"인간 뇌영상(MRI·PET·EEG) 전문, 3–4천 명. 영상 바이오마커 연구에 최적.",
  url:"https://www.humanbrainmapping.org/ohbm-2027/",
  dl:[{l:"초록 마감", d:null, note:"2026년 12월 · 구체일 미공지"},{l:"등록 오픈", d:null, note:"2027년 1월"}]},
 {id:"aaic", cat:"dem", acro:"AAIC 2027", full:"Alzheimer's Association International Conference",
  start:"2027-07-18", end:"2027-07-21", dateKo:"7월 18–21일", city:"시카고", country:"미국", flag:"🇺🇸",
  venue:"McCormick Place", hybrid:true, status:"ok",
  scale:"세계 최대 AD 학회(약 1만 명), 기초–임상 전 영역. 사전 워크숍 7/16–17, AAIC For All(임상가) 7/22.",
  url:"https://aaic.alz.org/",
  dl:[{l:"초록 접수", d:null, note:"2026년 가을 오픈 · 마감 미공지(통상 1월 말–2월 초)"},{l:"등록 오픈", d:null, note:"2027년 봄"}]},
 {id:"ibro", cat:"neuro", acro:"IBRO 2027", full:"12th IBRO World Congress of Neuroscience",
  start:"2027-09-13", end:"2027-09-16", dateKo:"9월 13–16일", city:"케이프타운", country:"남아공", flag:"🇿🇦",
  venue:"CTICC (Cape Town Intl. Convention Centre)", hybrid:false, status:"ok",
  scale:"4년 주기 세계대회, 최초의 아프리카 개최. 기초신경과학 종합(4–5천 명).",
  url:"https://ibro.org/event/ibro-2027-world-congress/",
  dl:[{l:"초록 마감", d:null, note:"미공지"},{l:"등록 오픈", d:null, note:"2027년 1월"}]},
 {id:"ecnp", cat:"psych", acro:"ECNP 2027", full:"40th ECNP Congress (European College of Neuropsychopharmacology)",
  start:"2027-09-25", end:"2027-09-28", dateKo:"9월 25–28일", city:"바르셀로나", country:"스페인", flag:"🇪🇸",
  venue:"CCIB", hybrid:false, status:"ok",
  scale:"유럽 최대 응용뇌과학·신경정신약리학 학회(약 7,600명). ※ MDS와 일정 중복.",
  url:"https://www.ecnp.eu/meetings/", dl:[{l:"초록 마감", d:null, note:"미공지 · 통상 대회 연도 봄"}]},
 {id:"mds", cat:"neuro", acro:"MDS 2027", full:"Intl. Congress of Parkinson's Disease and Movement Disorders",
  start:"2027-09-26", end:"2027-09-30", dateKo:"9월 26–30일", city:"암스테르담", country:"네덜란드", flag:"🇳🇱",
  venue:null, hybrid:false, status:"ok",
  scale:"운동질환 전문(5–7천 명). DLB·PDD 등 관련질환 스펙트럼 커버. ※ ECNP와 일정 중복.",
  url:"https://www.mdscongress.org/", dl:[{l:"초록 마감", d:null, note:"미공지"}]},
 {id:"sfn", cat:"neuro", acro:"SfN 2027", full:"Society for Neuroscience · Neuroscience 2027",
  start:"2027-10-23", end:"2027-10-27", dateKo:"10월 23–27일", city:"시카고", country:"미국", flag:"🇺🇸",
  venue:null, hybrid:false, status:"ok",
  scale:"세계 최대 기초신경과학 학회(2.5–3만 명). AD·신경퇴행 기초연구 세션 방대.",
  url:"https://www.sfn.org/meetings", dl:[{l:"초록 마감", d:null, note:"미공지 · 통상 5월"}]},
 {id:"wpa", cat:"psych", acro:"WPA 2027", full:"27th World Congress of Psychiatry",
  start:"2027-11-04", end:"2027-11-07", dateKo:"11월 4–7일", city:"카르타헤나", country:"콜롬비아", flag:"🇨🇴",
  venue:null, hybrid:false, status:"ok",
  scale:"세계정신의학회(WPA) 연례 세계대회, 대륙 순환 개최(2026 스톡홀름).",
  url:"https://www.wpanet.org/upcoming-congresses-events/", dl:[{l:"초록 마감", d:null, note:"미공지"}]},
 {id:"vascog", cat:"dem", acro:"VasCog 2027", full:"Intl. Society of Vascular Behavioural and Cognitive Disorders",
  start:"2027-11-13", end:"2027-11-16", dateKo:"11월 13–16일", city:"싱가포르", country:"싱가포르", flag:"🇸🇬",
  venue:null, hybrid:false, status:"ok",
  scale:"혈관성 인지장애(VCI) 특화 격년제 학회. 아시아 개최라 접근성 좋음.",
  url:"https://www.vascog.org/", dl:[{l:"초록 마감", d:null, note:"미공지"}]},
 /* ---- 의료 AI (2026-09-06 조사 추가) ---- */
 {id:"spie", cat:"ai", acro:"SPIE MI 2027", full:"SPIE Medical Imaging 2027",
  start:"2027-02-14", end:"2027-02-18", dateKo:"2월 14–18일", city:"밴쿠버", country:"캐나다", flag:"🇨🇦",
  venue:null, hybrid:false, status:"ok",
  scale:"의료영상 물리·CAD 전통의 공학 학회. 정규 초록은 2026-08-05 마감됨 — 2027 발표는 late submission(주최 승인)만 가능.",
  url:"https://spie.org/conferences-and-exhibitions/medical-imaging",
  dl:[{l:"초록 마감", d:"2026-08-05", note:"마감됨"},{l:"프로시딩 원고 마감", d:"2027-01-27"}]},
 {id:"isbi", cat:"ai", acro:"IEEE ISBI 2027", full:"IEEE International Symposium on Biomedical Imaging · 24th",
  start:"2027-05-25", end:"2027-05-28", dateKo:"5월 25–28일", city:"로잔", country:"스위스", flag:"🇨🇭",
  venue:"EPFL · SwissTech Convention Center", hybrid:false, status:"ok",
  scale:"IEEE 생의학 영상 대표 학회, 25주년 기념 완전 대면 개최. 4쪽 논문 포맷으로 문턱이 낮아 대학원생 첫 국제 발표 무대로 유용. ※ FENS Regional(5/26–29)과 중복.",
  url:"https://biomedicalimaging.org/2027/",
  dl:[{l:"워크숍·챌린지 제안 마감", d:"2026-09-21"},{l:"4쪽 논문 마감", d:"2026-10-26"},{l:"논문 채택 통보", d:"2027-01-12"},{l:"1쪽 초록 마감", d:"2027-02-01"}]},
 {id:"siim", cat:"ai", acro:"SIIM 2027", full:"Society for Imaging Informatics in Medicine Annual Meeting",
  start:"2027-06-17", end:"2027-06-19", dateKo:"6월 17–19일", city:"내슈빌", country:"미국", flag:"🇺🇸",
  venue:"Music City Center", hybrid:true, status:"ok",
  scale:"영상정보학·임상 AI 배포(PACS 통합·규제·워크플로) 중심. 연구 발표보다 임상 구현·산업 접점 참고용. ※ ILBDC(6/16–18)와 중복.",
  url:"https://siim.org/event/siim27-annual-meeting-informaticstech-expo/",
  dl:[{l:"세션 제안 마감", d:null, note:"공모 진행 중 · 마감일 미공지"}]},
 {id:"ipmi", cat:"ai", acro:"IPMI 2027", full:"30th Information Processing in Medical Imaging (격년제)",
  start:"2027-06-27", end:"2027-07-02", dateKo:"6/27–7/2", city:"오포드(퀘벡)", country:"캐나다", flag:"🇨🇦",
  venue:"Jouvence Centre, Lake Stukely", hybrid:false, status:"ok",
  scale:"격년제 소수정예(100–150명) 합숙형 학회 — 의료영상 계산 방법론 최고 심도 토론장(MICCAI 연계). 뇌영상 AI 방법론 랩이라면 MICCAI와 상보적 최상위 타깃. ※ OHBM(6/26–30)과 중복.",
  url:"https://2027.ipmi-conf.org/",
  dl:[{l:"논문 마감", d:"2026-12-07", note:"연장 없음"},{l:"채택 통보", d:"2027-02-15"}]},
 {id:"aime", cat:"ai", acro:"AIME 2027", full:"25th International Conference on Artificial Intelligence in Medicine",
  start:"2027-07-05", end:"2027-07-08", dateKo:"7월 5–8일", city:"암스테르담", country:"네덜란드", flag:"🇳🇱",
  venue:"KIT (Royal Tropical Institute)", hybrid:false, status:"ok",
  scale:"유럽 의학 AI 학술 학회(중소규모, Springer LNAI 프로시딩). 임상 의사결정지원·예측모델 중심 — 임상 배경 연구자의 유럽 네트워크 구축에 유리.",
  url:"https://aimedicine.info/", dl:[{l:"논문 마감", d:null, note:"미공지 · 통상 12월–1월"}]},
 {id:"midl", cat:"ai", acro:"MIDL 2027", full:"Medical Imaging with Deep Learning",
  start:"2027-07-14", end:"2027-07-16", dateKo:"7월 14–16일", city:"포르투", country:"포르투갈", flag:"🇵🇹",
  venue:null, hybrid:false, status:"ok",
  scale:"딥러닝 특화 의료영상 학회(중규모, OpenReview 공개 리뷰). 방법론·재현성 중심 — 뇌영상 딥러닝 모델 발표에 적합. 직후 AAIC 시카고(7/18–21)와 연속 주간.",
  url:"https://2027.midl.io/", dl:[{l:"논문 마감", d:null, note:"미공지 · 통상 1–2월"}]},
 {id:"miccai", cat:"ai", acro:"MICCAI 2027", full:"30th Intl. Conference on Medical Image Computing and Computer Assisted Intervention",
  start:"2027-09-27", end:"2027-10-01", dateKo:"9/27–10/1", city:"오클랜드", country:"뉴질랜드", flag:"🇳🇿",
  venue:null, hybrid:false, status:"ok",
  scale:"의료영상 AI 최대·최고 권위 학회(30회, 수천 명). 뇌 MRI·PET 분할, 질환 분류, 영상 바이오마커 등 AD 뇌영상 AI 연구의 핵심 무대. ※ 하와이→오클랜드로 개최지 변경됨 · ECNP/MDS(9월 말)와 중복.",
  url:"https://miccai.org/", dl:[{l:"논문 마감", d:null, note:"미공지 · 통상 2월 말"}]},
 {id:"amia", cat:"ai", acro:"AMIA 2027", full:"AMIA Annual Symposium (American Medical Informatics Association)",
  start:"2027-11-06", end:"2027-11-10", dateKo:"11월 6–10일", city:"샌디에이고", country:"미국", flag:"🇺🇸",
  venue:"Hilton San Diego Bayfront", hybrid:false, status:"ok",
  scale:"미국 의료정보학 대표 학회(2천+ 명). EHR·임상 NLP·표현형 분석 등 임상데이터 연구 접점 — 디지털 바이오마커 연구와 연결. ※ WPA(11/4–7)와 중복 · 일정은 공식 사이트 재확인 권장.",
  url:"https://amia.org/education-events/annual-symposium", dl:[{l:"논문·패널 마감", d:null, note:"미공지 · 통상 3월 중순"}]},
 {id:"rsna", cat:"ai", acro:"RSNA 2027", full:"Radiological Society of North America · 113th Annual Meeting",
  start:"2027-11-14", end:"2027-11-18", dateKo:"11월 14–18일", city:"시카고", country:"미국", flag:"🇺🇸",
  venue:"McCormick Place", hybrid:false, status:"ok",
  scale:"세계 최대 영상의학 학회(4만+ 명, 대규모 AI Showcase). 2027년부터 11월 중순 조기 개최로 전환된 첫 해. 임상 영상 AI 상용화 동향 파악에 최적. ※ VasCog(11/13–16)와 중복.",
  url:"https://www.rsna.org/annual-meeting", dl:[{l:"초록 마감", d:null, note:"미공지 · 통상 5월 초"}]}
];

const TBA = [
 {id:"ctad", acro:"CTAD 2027", cat:"dem", txt:"AD 임상시험 특화(약 2천 명) — 신약 topline 발표 무대. 2027(20회) 일정 미공지, 통상 10월 말–12월 초. 참고: 2026년은 11/16–19 보스턴.", url:"https://www.ctad-alzheimer.com/"},
 {id:"ipa", acro:"IPA 2027", cat:"psych", txt:"국제노인정신의학회 — 치매·노인정신의학 특화로 가장 직접 관련. 개최지 파도바(이탈리아)만 확정, 날짜 미공지(통상 여름–초가을).", url:"https://www.ipa-online.org/events/annual-congress"},
 {id:"isftd", acro:"ISFTD", cat:"dem", txt:"FTD 특화 격년제 — 2027년 개최 없음(2026년 10/8–11 필라델피아, 차기 2028년 유럽 예상).", url:"https://www.isftd.org/"},
 {id:"adi", acro:"ADI", cat:"dem", txt:"격년제 — 2027년 개최 없음. 차기 38차 대회는 2028년 3월 8–10일 뉴델리. 정책·케어·옹호 중심.", url:"https://www.alzint.org/what-we-do/adi-conference/"},
 {id:"cinp", acro:"CINP", cat:"psych", txt:"2027 아부다비 세계대회 취소됨. 차기 세계대회는 2028년 6월 21–24일 리우데자네이루.", url:"https://cinp.org/congress"},
 {id:"chil", acro:"CHIL 2027", cat:"ai", txt:"헬스케어 ML 방법론 중심 소규모 정예 학회 — 통상 6월 말 북미 개최(2026년은 6/28–30 시애틀). 2027 일정·장소 미발표.", url:"https://chil.ahli.cc/"},
 {id:"ml4h", acro:"ML4H 2027", cat:"ai", txt:"NeurIPS 시즌(12월 초)에 열리는 헬스케어 ML 심포지엄(2026년은 12/6–7 시드니). 2027 일정 미발표 — NeurIPS 개최지 발표에 연동될 전망.", url:"https://ahli.cc/ml4h/"}
];
